project:
  type: website
  render:
    - "*.qmd"
  output-dir: /home/paul/526/ECON526/lectures/paul

website:
  title: "ECON 526"
  navbar:
    left:
      - href: index.qmd
        text: Content
      - href: https://github.com/ubcecon/econ526
        text: Github
      - text: Slides from Jesse
        href: https://jlperla.github.io/grad_econ_datascience/
      - href: feed.qmd
        text: Feed

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
