---
title: "ECON 526: Quantitative Economics with Data Science Applications"
author: "Paul Schrimpf"
bibliography: 526.bib
---

# Slides

1. [Introduction to Causality](causality_intro.qmd), [notebook](causality_intro.ipynb)
   - Reading: [Chapter 2](https://causalml-book.org/assets/chapters/CausalML_chap_2.pdf) of @causalml2024 or [Chapter 1](https://matheusfacure.github.io/python-causality-handbook/01-Introduction-To-Causality.html) of @facure2022

2. [Uncertainty Quantification](uncertainty.qmd), [notebook](uncertainty.ipynb)
   - [Chapter 3](https://matheusfacure.github.io/python-causality-handbook/03-Stats-Review-The-Most-Dangerous-Equation.html.html) of @facure2022

3. [Linear regression](regression.qmd), [notebook](regression.ipynb)
   - Chapters 5-7 of @facure2022 or Chapters 1-2 of @causalml2024

4. [Matching slides](matching.qmd), [notebook](matching.ipynb)
   - [Chapters 10-12](https://matheusfacure.github.io/python-causality-handbook/10-Matching.html) of @facure2022
   - [Chapter 14](https://theeffectbook.net/ch-Matching.html) of @hk2021
   - Chapters 5 and 10 of @causalml2024

5. [Introduction to difference in differences](did.qmd), [notebook](did.ipynb)
   - Reading: [chapter 13](https://matheusfacure.github.io/python-causality-handbook/13-Difference-in-Differences.html) of @facure2022

6. [Fixed Effects](fe.qmd), [notebook](fe.ipynb)
   - Reading: [chapter 14](https://matheusfacure.github.io/python-causality-handbook/14-Panel-Data-and-Fixed-Effects.html) of @facure2022

7. [Advanced difference in differences](moredid.qmd), [notebook](moredid.ipynb)
   - Reading: [chapter 24](https://matheusfacure.github.io/python-causality-handbook/24-The-Diff-in-Diff-Saga.html) of @facure2022, @roth2023, @dd2022

9. [Instrumental Variables](iv.qmd), [notebook](iv.ipynb)
   - Reading: [Chapter 8 and 9](https://matheusfacure.github.io/python-causality-handbook/08-Instrumental-Variables.html) of @facure2022


8. [Synthetic Control](syntheticcontrol.qmd), [notebook](syntheticcontrol.ipynb)
   - Reading: @abadie2021,[chapter 15](https://matheusfacure.github.io/python-causality-handbook/15-Synthetic-Control.html) of @facure2022


10. [Debiased Machine Learning](doubleml.qmd), [notebook](doubleml.ipynb)
   - Reading: [QuantEcon: ML in Economics](https://datascience.quantecon.org/applications/ml_in_economics.html#estimation-of-nuisance-functions)

11. [Treatment Heterogeneity and Conditional Effects](conditionaleffect.qmd), [notebook](conditionaleffect.ipynb)
   - Reading: [QuantEcon: Heterogeneity](https://datascience.quantecon.org/applications/heterogeneity.html)

13. [Regression discontinuity](rdd.qmd), [notebook](rdd.ipynb)

12. [Neural Networks](neuralnets.qmd), [notebook](neuralnets.ipynb)
   - Reading: [QuantEcon Datascience: Regression - Neural Networks](https://datascience.quantecon.org/tools/regression.html#neural-networks)
